<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKvz4lSa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKvz4lSa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKvz4lSa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKvz4lSa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKvz4lSa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Kvz4lSa',
    'container.build_id' => 'd7a17d92',
    'container.build_time' => 1579863417,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKvz4lSa');
